<aside class="w-68 flex h-screen shrink-0 flex-col overflow-y-auto border-r border-slate-800 bg-slate-900 text-slate-100 lg:sticky lg:top-0 lg:self-start">
    <div class="flex items-center space-x-3 border-b border-slate-800 p-6">
        <div class="flex h-8 w-8 items-center justify-center rounded bg-indigo-600 text-white shadow-md"><i class="fa-solid fa-clock-rotate-left text-sm" aria-hidden="true"></i></div>
        <div><span class="block text-lg font-semibold tracking-tight text-white">WorkLive <span class="font-bold text-indigo-400">Pro</span></span><span class="font-mono text-xs text-slate-500">Live Operations</span></div>
    </div>
    @php($links=[['dashboard','dashboard','Tablero Principal','fa-solid fa-table-columns'],['employees','employees*','Lista de Empleados','fa-solid fa-users'],['reports','reports*','Reportes y Exportación','fa-solid fa-chart-column'],['policies','policies*','Políticas de Uso','fa-solid fa-shield-halved'],['time-clock','time-clock','RH · Reloj Checador','fa-solid fa-user-clock'],['settings','settings*','Configuración','fa-solid fa-gear']])
    <nav class="flex-1 space-y-1.5 p-4"><span class="mb-2 block px-3 font-mono text-[10px] font-semibold uppercase tracking-widest text-slate-500">Administrador</span>@foreach($links as [$route,$active,$label,$icon])<a href="{{ route($route) }}" class="flex w-full items-center space-x-3 rounded-md px-3 py-2 text-sm font-medium transition-all {{ request()->routeIs($active) ? 'bg-indigo-600 text-white shadow' : 'text-slate-300 hover:bg-slate-800 hover:text-white' }}"><i class="w-4 text-center text-sm {{ $icon }}" aria-hidden="true"></i><span>{{ $label }}</span></a>@endforeach</nav>
    <div class="mx-3 mb-4 flex items-center justify-between rounded-xl border border-slate-800/80 bg-slate-800/40 p-4"><div class="flex items-center space-x-2"><span class="relative flex h-2 w-2"><span class="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75"></span><span class="relative inline-flex h-2 w-2 rounded-full bg-emerald-500"></span></span><span class="text-xs font-medium text-slate-400">MySQL Sync</span></div><span class="font-mono text-[10px] text-slate-500">Real-time</span></div>
    <div class="mt-auto border-t border-slate-800 bg-slate-950/40 p-4"><div class="mb-3.5 flex items-center space-x-2.5"><div class="flex h-9 w-9 items-center justify-center rounded-full border border-slate-600 bg-slate-700 text-xs font-bold">{{ mb_strtoupper(mb_substr(session('worklive_admin.email','A'),0,1)) }}</div><div class="min-w-0 flex-1"><p class="truncate text-xs font-semibold text-slate-200">Admin WorkLive</p><p class="truncate font-mono text-[10px] text-slate-400">{{ session('worklive_admin.email') }}</p></div></div><form method="post" action="{{ route('logout') }}">@csrf<button class="flex w-full items-center justify-center space-x-1.5 rounded-lg border border-slate-800 px-3 py-2 text-xs font-medium text-slate-400 transition-all hover:border-red-900/40 hover:bg-red-950/20 hover:text-red-400" type="submit"><i class="fa-solid fa-right-from-bracket" aria-hidden="true"></i><span>Cerrar sesión</span></button></form></div>
</aside>
