@extends('layouts.app')

@section('body')
@php
    $decode = fn($value) => is_array($value) ? $value : (json_decode($value ?: '[]', true) ?: []);
    $activeMembers = $active ? ($membersByPolicy->get($active->id, collect())->pluck('employee_id')->all()) : [];
    $assigned = collect($membersByPolicy)->flatMap(fn($members, $profileId) => $members->pluck('employee_id')->mapWithKeys(fn($employeeId) => [$employeeId => $profileId]))->all();
    $presetJson = [
        ['name'=>'Redes sociales','tone'=>'sky','description'=>'Facebook, X/Twitter, Instagram, TikTok, LinkedIn y similares.','domains'=>['facebook.com','fb.com','instagram.com','threads.net','x.com','twitter.com','tiktok.com','snapchat.com','pinterest.com','reddit.com','linkedin.com'],'apps'=>['Facebook','Instagram','Threads','X','Twitter','TikTok','Snapchat','Pinterest','Reddit','LinkedIn']],
        ['name'=>'Multimedia','tone'=>'red','description'=>'Video corto, plataformas de video y entretenimiento visual.','domains'=>['youtube.com','youtu.be','vimeo.com','dailymotion.com','twitch.tv','kick.com'],'apps'=>['YouTube','Vimeo','Dailymotion','Twitch','Kick']],
        ['name'=>'Streaming','tone'=>'violet','description'=>'Películas, series y servicios de TV bajo demanda.','domains'=>['netflix.com','primevideo.com','disneyplus.com','max.com','hbomax.com','hulu.com','paramountplus.com','peacocktv.com','tv.apple.com'],'apps'=>['Netflix','Prime Video','Disney+','Max','HBO Max','Hulu','Paramount+','Peacock','Apple TV']],
        ['name'=>'Música','tone'=>'emerald','description'=>'Audio, playlists, radio y plataformas musicales.','domains'=>['spotify.com','music.apple.com','music.youtube.com','soundcloud.com','deezer.com','tidal.com','pandora.com','iheart.com'],'apps'=>['Spotify','Apple Music','YouTube Music','SoundCloud','Deezer','Tidal','Pandora','iHeartRadio']],
        ['name'=>'Juegos y ocio','tone'=>'amber','description'=>'Launchers, juegos y comunidades recreativas.','domains'=>['steampowered.com','steamcommunity.com','epicgames.com','roblox.com','battle.net','ea.com'],'apps'=>['Steam','Epic Games Launcher','Roblox','Battle.net','EA app','Xbox','PlayStation']],
        ['name'=>'Chat personal','tone'=>'cyan','description'=>'Mensajería personal o comunidades fuera del flujo laboral.','domains'=>['web.whatsapp.com','telegram.org','discord.com','messenger.com','wechat.com','line.me'],'apps'=>['WhatsApp','Telegram','Discord','Messenger','WeChat','LINE']],
    ];
    $tone = ['sky'=>'border-sky-100 bg-sky-50 text-sky-700','red'=>'border-red-100 bg-red-50 text-red-700','violet'=>'border-violet-100 bg-violet-50 text-violet-700','emerald'=>'border-emerald-100 bg-emerald-50 text-emerald-700','amber'=>'border-amber-100 bg-amber-50 text-amber-700','cyan'=>'border-cyan-100 bg-cyan-50 text-cyan-700'];
    $draft = $active ? ['name'=>$active->name,'description'=>$active->description,'blocked_domains'=>$decode($active->blocked_domains),'allowed_domains'=>$decode($active->allowed_domains),'productive_apps'=>$decode($active->productive_apps),'unproductive_apps'=>$decode($active->unproductive_apps),'blocked_apps'=>$decode($active->blocked_apps)] : ['name'=>'Nueva política','description'=>'Perfil de uso empresarial','blocked_domains'=>[],'allowed_domains'=>[],'productive_apps'=>[],'unproductive_apps'=>[],'blocked_apps'=>[]];
    $policyCount = $policies->count();
    $assignedCount = count($assigned);
    $ruleCount = count($draft['blocked_domains']) + count($draft['allowed_domains']) + count($draft['productive_apps']) + count($draft['unproductive_apps']) + count($draft['blocked_apps']);
@endphp
<div class="shell">@include('partials.sidebar')<main class="main">@include('partials.header',['title'=>'Políticas de Uso Empresarial'])
<div class="content policy-workspace"><section class="policy-hero mb-6"><div class="policy-hero-copy"><p><i class="fa-solid fa-shield-halved" aria-hidden="true"></i> Centro de control</p><h2>Políticas de uso</h2><span>Define qué se permite, clasifica el foco del equipo y distribuye reglas a los agentes vinculados.</span></div><div class="policy-hero-metrics"><div><i class="fa-solid fa-layer-group" aria-hidden="true"></i><small>Perfiles</small><b>{{ $policyCount }}</b></div><div><i class="fa-solid fa-users" aria-hidden="true"></i><small>Asignados</small><b>{{ $assignedCount }}</b></div><div><i class="fa-solid fa-list-check" aria-hidden="true"></i><small>Reglas activas</small><b>{{ $ruleCount }}</b></div></div><div class="policy-hero-actions"><form method="post" action="{{ route('policies.push') }}">@csrf<button title="Envía la política vigente a los agentes conectados"><i class="fa-solid fa-paper-plane" aria-hidden="true"></i><span>Enviar actualización</span></button></form><a href="{{ route('policies',['new'=>1]) }}"><i class="fa-solid fa-plus" aria-hidden="true"></i><span>Nuevo perfil</span></a></div></section>
@if(session('success'))<div class="mb-5 flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-semibold text-emerald-700">✓ {{ session('success') }}</div>@endif @if($errors->any())<div class="mb-5 flex items-center gap-2 rounded-xl border border-red-100 bg-red-50 p-4 text-xs font-semibold text-red-700">⚠ {{ $errors->first() }}</div>@endif
<div class="grid grid-cols-1 gap-6 xl:grid-cols-12"><aside class="h-max rounded-2xl border border-slate-100 bg-white p-4 shadow-sm xl:col-span-3"><span class="font-mono text-[10px] font-black uppercase text-slate-400">Perfiles</span><div class="mt-3 space-y-2">@forelse($policies as $profile)@php($count=$membersByPolicy->get($profile->id,collect())->count())<a href="{{ route('policies',['policy'=>$profile->id]) }}" class="block rounded-xl border p-3 transition {{ $active?->id===$profile->id ? 'border-indigo-200 bg-indigo-50 text-indigo-900' : 'border-slate-100 bg-slate-50/60 text-slate-700 hover:bg-slate-100' }}"><b class="block text-xs">{{ $profile->name }}</b><span class="mt-1 block text-[10px] text-slate-400">{{ $count }} usuarios asignados</span></a>@empty<p class="py-6 text-center text-xs text-slate-400">Aún no hay perfiles.</p>@endforelse</div></aside>
<section class="space-y-6 xl:col-span-9"><form id="policy-form" method="post" action="{{ $active ? route('policies.update',$active->id) : route('policies.store') }}">@csrf @if($active) @method('PUT') @endif
<div class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div class="grid grid-cols-1 gap-5 md:grid-cols-2"><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold uppercase text-slate-400">Nombre del perfil</span><input class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-800" name="name" required value="{{ old('name',$draft['name']) }}"></label><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold uppercase text-slate-400">Descripción</span><input class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-800" name="description" value="{{ old('description',$draft['description']) }}"></label></div></div>
<div class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div class="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h3 class="text-sm font-bold text-slate-900">Catálogo predeterminado</h3><p class="mt-1 text-xs text-slate-400">Selecciona categorías completas y luego quita elementos uno por uno.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 font-mono text-[10px] font-bold text-slate-500">{{ count($presetJson) }} categorías listas</span></div><div class="grid grid-cols-1 gap-4 lg:grid-cols-2">@foreach($presetJson as $preset)<article class="rounded-2xl border p-4 {{ $tone[$preset['tone']] }}"><div class="flex items-start justify-between gap-3"><div><h4 class="font-mono text-xs font-black uppercase">{{ $preset['name'] }}</h4><p class="mt-1 text-[11px] opacity-80">{{ $preset['description'] }}</p></div><span class="shrink-0 rounded-full bg-white/70 px-2 py-1 text-[10px] font-bold">{{ count($preset['domains'])+count($preset['apps']) }} items</span></div><div class="mt-3 flex flex-wrap gap-1.5">@foreach(array_slice($preset['domains'],0,5) as $domain)<span class="rounded-lg bg-white/70 px-2 py-1 text-[10px] font-semibold">{{ $domain }}</span>@endforeach @if(count($preset['domains'])>5)<span class="rounded-lg bg-white/50 px-2 py-1 text-[10px] font-semibold">+{{ count($preset['domains'])-5 }} dominios</span>@endif</div><div class="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-3"><button type="button" class="policy-preset rounded-xl bg-white/80 px-3 py-2 text-[10px] font-black uppercase hover:bg-white" data-target="blocked_domains" data-values='@json($preset['domains'])'>Bloquear sitios</button><button type="button" class="policy-preset rounded-xl bg-white/80 px-3 py-2 text-[10px] font-black uppercase hover:bg-white" data-target="unproductive_apps" data-values='@json($preset['apps'])'>Apps no productivas</button><button type="button" class="policy-preset rounded-xl bg-white/80 px-3 py-2 text-[10px] font-black uppercase hover:bg-white" data-target="blocked_apps" data-values='@json($preset['apps'])'>Bloquear apps</button></div></article>@endforeach</div></div>
<div class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 class="mb-3 text-sm font-bold text-slate-900">⇩ Importación rápida</h3><div class="grid grid-cols-1 gap-3 md:grid-cols-4"><select id="bulk-target" class="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-700"><option value="blocked_domains">Sitios bloqueados</option><option value="allowed_domains">Sitios productivos</option><option value="productive_apps">Apps productivas</option><option value="unproductive_apps">Apps no productivas</option><option value="blocked_apps">Apps bloqueadas</option></select><textarea id="bulk-values" class="min-h-20 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs md:col-span-2" placeholder="youtube.com, netflix.com&#10;tiktok.com"></textarea><button id="bulk-import" type="button" class="h-10 rounded-xl bg-slate-900 text-xs font-bold text-white hover:bg-slate-800">⇩ Importar</button></div></div>
<div class="grid grid-cols-1 gap-5 lg:grid-cols-2">@foreach(['blocked_domains'=>'Sitios bloqueados','allowed_domains'=>'Sitios productivos','productive_apps'=>'Apps productivas','unproductive_apps'=>'Apps no productivas','blocked_apps'=>'Apps bloqueadas'] as $field=>$label)<div class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div class="mb-3 flex items-center justify-between"><div><h3 class="font-mono text-xs font-black uppercase text-slate-900">{{ $label }}</h3><p id="{{ $field }}-count" class="text-[11px] text-slate-400"></p></div><button class="select-target rounded-lg bg-slate-100 px-2 py-1 font-mono text-[10px] font-bold text-slate-500" type="button" data-target="{{ $field }}">Importar aquí</button></div><div id="{{ $field }}-chips" class="flex min-h-12 flex-wrap gap-2"></div><input id="{{ $field }}" type="hidden" name="{{ $field }}" value="{{ implode(',', old($field,$draft[$field])) }}"></div>@endforeach</div>
<div class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 class="mb-4 text-sm font-bold text-slate-900">◇ Usuarios asignados</h3><div class="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">@foreach($employees as $employee)@php($elsewhere=isset($assigned[$employee->id]) && $assigned[$employee->id] !== ($active?->id ?? ''))<label class="flex items-center gap-3 rounded-xl border p-3 text-xs {{ in_array($employee->id,$activeMembers,true) ? 'border-indigo-200 bg-indigo-50' : ($elsewhere ? 'border-slate-100 bg-slate-100 opacity-60' : 'border-slate-100 bg-slate-50') }}"><input class="accent-indigo-600" type="checkbox" name="member_employee_ids[]" value="{{ $employee->id }}" @checked(in_array($employee->id,old('member_employee_ids',$activeMembers),true)) @disabled($elsewhere)><span><b class="block text-slate-800">{{ $employee->name }}</b><small class="text-slate-400">{{ $employee->department }}</small></span></label>@endforeach</div></div>
<div class="flex flex-col justify-end gap-3 sm:flex-row">@if($active)</form><form method="post" action="{{ route('policies.delete',$active->id) }}" onsubmit="return confirm('¿Eliminar la política {{ addslashes($active->name) }}?')">@csrf @method('DELETE')<button class="flex w-full items-center justify-center gap-2 rounded-xl bg-red-50 px-5 py-2.5 text-xs font-bold text-red-700 hover:bg-red-100 sm:w-auto">⌫ Eliminar</button></form><form id="policy-submit" method="post" action="{{ route('policies.update',$active->id) }}">@csrf @method('PUT')@else</form><form id="policy-submit" method="post" action="{{ route('policies.store') }}">@csrf @endif<button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-indigo-500" type="submit">▣ Guardar Política</button></form></div>
</section></div></div></main></div>
<script>
(() => {
    const fields = ['blocked_domains', 'allowed_domains', 'productive_apps', 'unproductive_apps', 'blocked_apps'];
    const lists = {};
    fields.forEach((field) => {
        const input = document.getElementById(field);
        lists[field] = (input.value || '').split(/[;,\n]+/).map((value) => value.trim().replace(/^https?:\/\//, '').replace(/^www\./, '')).filter(Boolean);
    });
    const unique = (items) => [...new Set(items.map((item) => item.trim()).filter(Boolean))].sort((a, b) => a.localeCompare(b));
    const render = (field) => {
        lists[field] = unique(lists[field]);
        document.getElementById(field).value = lists[field].join(',');
        document.getElementById(field + '-count').textContent = lists[field].length === 1 ? '1 elemento' : lists[field].length + ' elementos';
        document.getElementById(field + '-chips').innerHTML = lists[field].map((value) => `<span class="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-slate-50 px-2 py-1 text-[10px] font-semibold text-slate-700">${value.replace(/</g, '&lt;')}<button type="button" class="remove-chip text-slate-400 hover:text-red-600" data-field="${field}" data-value="${encodeURIComponent(value)}">×</button></span>`).join('');
    };
    fields.forEach(render);
    document.addEventListener('click', (event) => {
        const remove = event.target.closest('.remove-chip');
        if (remove) { const field = remove.dataset.field, value = decodeURIComponent(remove.dataset.value); lists[field] = lists[field].filter((item) => item !== value); render(field); }
        const preset = event.target.closest('.policy-preset');
        if (preset) { lists[preset.dataset.target].push(...JSON.parse(preset.dataset.values)); render(preset.dataset.target); }
        const select = event.target.closest('.select-target');
        if (select) { document.getElementById('bulk-target').value = select.dataset.target; document.getElementById('bulk-values').focus(); }
        if (event.target.id === 'bulk-import') { const field = document.getElementById('bulk-target').value; lists[field].push(...document.getElementById('bulk-values').value.split(/[;,\n]+/)); render(field); document.getElementById('bulk-values').value = ''; }
    });
    const source = document.getElementById('policy-form'), target = document.getElementById('policy-submit');
    const appendHidden = (name, value) => { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = value; input.dataset.policySubmitField = 'true'; target.appendChild(input); };
    target.addEventListener('submit', (event) => {
        event.preventDefault();
        target.querySelectorAll('[data-policy-submit-field]').forEach((input) => input.remove());
        fields.forEach((field) => appendHidden(field, document.getElementById(field).value));
        source.querySelectorAll('input[name="member_employee_ids[]"]:checked').forEach((input) => appendHidden('member_employee_ids[]', input.value));
        ['name', 'description'].forEach((name) => appendHidden(name, source.querySelector(`[name="${name}"]`).value));
        target.submit();
    });
})();
</script>
@endsection
