@extends('layouts.app')

@section('body')
@php
    $fmt = fn($seconds) => intdiv((int) $seconds, 3600).'h '.str_pad((string) intdiv(((int) $seconds % 3600), 60), 2, '0', STR_PAD_LEFT).'m';
    $tabs = ['overview' => ['Resumen', '▦'], 'attendance' => ['Asistencia', '◷'], 'productivity' => ['Productividad', '↗'], 'incidents' => ['Incidencias', '⚠']];
    $query = request()->except('tab', 'page');
@endphp
<div class="flex min-h-screen overflow-hidden bg-slate-100/45 font-sans text-slate-800">
@include('partials.sidebar')
<main class="flex min-w-0 flex-1 flex-col overflow-hidden bg-slate-50/20">
@include('partials.header',['title'=>'Centro de Reportes'])
<div class="flex-1 overflow-y-auto bg-slate-50/60 p-6 lg:p-8">
    <section class="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
        <div><p class="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-indigo-500">Inteligencia operativa</p><h2 class="mt-1 text-2xl font-black tracking-tight text-slate-950">Reportes y exportación</h2><p class="mt-1 text-xs text-slate-500">Consolidado de <b>{{ $from }}</b> a <b>{{ $to }}</b> · Zona {{ str_replace('_', ' ', $corporateTimezone) }}</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('reports.export.pdf', request()->query()) }}" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-600 shadow-sm transition hover:border-indigo-200 hover:text-indigo-700">▣ PDF</a><a href="{{ route('reports.export.xlsx', request()->query()) }}" class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-bold text-emerald-700 shadow-sm transition hover:bg-emerald-100">↓ Excel</a><a href="{{ route('reports.export', request()->query()) }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white shadow-md shadow-indigo-200 transition hover:bg-indigo-500">↓ CSV detallado</a></div>
    </section>

    <form method="get" class="mb-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
        <input type="hidden" name="tab" value="{{ $tab }}">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">
            <label><span class="mb-1.5 block font-mono text-[9px] font-bold uppercase tracking-wider text-slate-400">Desde</span><input type="date" name="date_from" value="{{ $from }}" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold outline-none focus:border-indigo-400 focus:bg-white"></label>
            <label><span class="mb-1.5 block font-mono text-[9px] font-bold uppercase tracking-wider text-slate-400">Hasta</span><input type="date" name="date_to" value="{{ $to }}" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold outline-none focus:border-indigo-400 focus:bg-white"></label>
            <label><span class="mb-1.5 block font-mono text-[9px] font-bold uppercase tracking-wider text-slate-400">Colaborador</span><select name="employee_id" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold outline-none focus:border-indigo-400 focus:bg-white"><option value="All">Todos los colaboradores</option>@foreach($employees as $employee)<option value="{{ $employee->employee_id }}" @selected(request('employee_id','All') === $employee->employee_id)>{{ $employee->employee_name }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block font-mono text-[9px] font-bold uppercase tracking-wider text-slate-400">Departamento</span><select name="department" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold outline-none focus:border-indigo-400 focus:bg-white"><option value="All">Todos los departamentos</option>@foreach($departments as $department)<option value="{{ $department }}" @selected(request('department','All') === $department)>{{ $department }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block font-mono text-[9px] font-bold uppercase tracking-wider text-slate-400">País</span><select name="country" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold outline-none focus:border-indigo-400 focus:bg-white"><option value="All">Todos los países</option>@foreach($countries as $country)<option value="{{ $country }}" @selected(request('country','All') === $country)>{{ $country }}</option>@endforeach</select></label>
        </div>
        <div class="mt-4 flex justify-end gap-2"><a href="{{ route('reports') }}" class="rounded-lg px-3 py-2 text-xs font-bold text-slate-500 hover:text-rose-600">Limpiar</a><button class="rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white hover:bg-slate-700">Actualizar reporte</button></div>
    </form>

    <section class="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-5">
        @foreach([['Colaboradores', $metrics->employees, 'text-slate-900', 'bg-slate-100'], ['Tiempo activo', $fmt($metrics->active), 'text-emerald-600', 'bg-emerald-50'], ['Tiempo inactivo', $fmt($metrics->idle), 'text-amber-600', 'bg-amber-50'], ['Productividad', $metrics->productivity.'%', 'text-indigo-600', 'bg-indigo-50'], ['Incidencias', $metrics->incidents, 'text-rose-600', 'bg-rose-50']] as [$label, $value, $tone, $bg])
        <article class="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><span class="inline-flex rounded-lg px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-wider {{ $bg }} {{ $tone }}">{{ $label }}</span><strong class="mt-3 block text-2xl font-black {{ $tone }}">{{ $value }}</strong></article>
        @endforeach
    </section>

    <nav class="mb-5 flex gap-2 overflow-x-auto border-b border-slate-200 pb-0">@foreach($tabs as $key => [$label, $icon])<a href="{{ route('reports', array_merge($query, ['tab' => $key])) }}" class="whitespace-nowrap border-b-2 px-4 py-3 text-xs font-bold transition {{ $tab === $key ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-slate-400 hover:text-slate-700' }}">{{ $icon }} {{ $label }}</a>@endforeach</nav>

    <section class="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm">
        @if($tab === 'incidents')
            <div class="border-b border-slate-100 p-5"><h3 class="font-bold text-slate-900">Incidencias y bloqueos</h3><p class="mt-1 text-xs text-slate-500">Eventos de bloqueo, sitios restringidos y sesiones bloqueadas dentro del periodo.</p></div>
            <div class="overflow-x-auto"><table class="min-w-[780px] w-full text-left text-xs"><thead class="bg-slate-50 font-mono text-[9px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Momento</th><th class="px-5 py-3">Empleado</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3">Aplicación / dominio</th><th class="px-5 py-3">Detalle</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($incidents as $event)<tr><td class="px-5 py-3 font-mono text-slate-500">{{ $event->display_timestamp->format('d/m/Y H:i') }}</td><td class="px-5 py-3 font-bold text-slate-800">{{ $event->employee_name }}</td><td class="px-5 py-3"><span class="rounded-full bg-rose-50 px-2 py-1 font-mono text-[9px] font-bold text-rose-700">{{ $event->event_type }}</span></td><td class="px-5 py-3 font-semibold text-slate-700">{{ $event->app ?: $event->domain ?: '—' }}</td><td class="px-5 py-3 text-slate-500">{{ $event->title ?: 'Sin detalle adicional' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-16 text-center text-xs text-slate-400">No hay incidencias para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
        @else
            <div class="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="font-bold text-slate-900">{{ $tab === 'attendance' ? 'Asistencia por colaborador' : ($tab === 'productivity' ? 'Productividad por colaborador' : 'Resumen por colaborador') }}</h3><p class="mt-1 text-xs text-slate-500">{{ $employeeRows->count() }} colaboradores con actividad consolidada en el periodo.</p></div><span class="rounded-lg bg-slate-50 px-3 py-1.5 font-mono text-[10px] font-bold text-slate-500">{{ $from }} → {{ $to }}</span></div>
            <div class="overflow-x-auto"><table class="min-w-[900px] w-full text-left text-xs"><thead class="bg-slate-50 font-mono text-[9px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Colaborador</th><th class="px-5 py-3">Departamento / País</th><th class="px-5 py-3 text-center">Días</th><th class="px-5 py-3 text-right">Activo</th><th class="px-5 py-3 text-right">Inactivo</th><th class="px-5 py-3 text-right">Bloqueado</th><th class="px-5 py-3 text-right">Productividad</th><th class="px-5 py-3 text-right">Jornada registrada</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($employeeRows->sortByDesc($tab === 'productivity' ? 'productivity' : 'active') as $row)<tr class="transition hover:bg-slate-50"><td class="px-5 py-4"><a href="{{ route('employees.show', $row->employee_id) }}" class="font-bold text-slate-900 hover:text-indigo-600">{{ $row->employee_name }}</a></td><td class="px-5 py-4"><span class="block font-semibold text-slate-600">{{ $row->department }}</span><span class="text-[10px] text-slate-400">{{ $row->country }}</span></td><td class="px-5 py-4 text-center font-mono text-slate-600">{{ $row->days }}</td><td class="px-5 py-4 text-right font-mono font-bold text-emerald-600">{{ $fmt($row->active) }}</td><td class="px-5 py-4 text-right font-mono text-amber-500">{{ $fmt($row->idle) }}</td><td class="px-5 py-4 text-right font-mono text-indigo-500">{{ $fmt($row->locked) }}</td><td class="px-5 py-4 text-right"><span class="inline-flex min-w-12 justify-center rounded-full px-2 py-1 font-mono text-[10px] font-bold {{ $row->productivity >= 75 ? 'bg-emerald-50 text-emerald-700' : ($row->productivity >= 50 ? 'bg-amber-50 text-amber-700' : 'bg-rose-50 text-rose-700') }}">{{ $row->productivity }}%</span></td><td class="px-5 py-4 text-right font-mono text-[10px] text-slate-500">{{ $row->first_activity ? \Carbon\Carbon::parse($row->first_activity, 'UTC')->setTimezone($corporateTimezone)->format('H:i') : '—' }} – {{ $row->last_activity ? \Carbon\Carbon::parse($row->last_activity, 'UTC')->setTimezone($corporateTimezone)->format('H:i') : '—' }}</td></tr>@empty<tr><td colspan="8" class="px-5 py-16 text-center text-xs text-slate-400">No existen resúmenes para el periodo seleccionado.</td></tr>@endforelse</tbody></table></div>
        @endif
    </section>
</div>
</main></div>
<style>@media print {.shell,.sidebar,header,form,nav,button,a[href],.no-print{display:none!important}.main,main,.content{overflow:visible!important;height:auto!important}.flex-1{overflow:visible!important}.shadow-sm{box-shadow:none!important}}</style>
@endsection
