<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DashboardApiController extends Controller
{
    private function company(): string { return config('worklive.company_id'); }
    private function jsonList($value): array { $decoded = is_string($value) ? json_decode($value, true) : $value; return is_array($decoded) ? array_values($decoded) : []; }

    public function settings()
    {
        $row = DB::table('company_settings')->where('company_id', $this->company())->first();
        return response()->json(['ok' => true, 'settings' => ['companyName' => $row->company_name ?? config('worklive.company_name'), 'businessHoursStart' => $row->business_hours_start ?? '08:00', 'businessHoursEnd' => $row->business_hours_end ?? '18:00', 'productiveAppsList' => $this->jsonList($row->productive_apps_list ?? []), 'unproductiveAppsList' => $this->jsonList($row->unproductive_apps_list ?? []), 'productiveDomainsList' => $this->jsonList($row->productive_domains_list ?? []), 'unproductiveDomainsList' => $this->jsonList($row->unproductive_domains_list ?? []), 'agentSampleIntervalSeconds' => (int) ($row->agent_sample_interval_seconds ?? 15), 'agentBatchIntervalSeconds' => (int) ($row->agent_batch_interval_seconds ?? 300), 'agentPollIntervalSeconds' => (int) ($row->agent_poll_interval_seconds ?? 30), 'blockWebsitesEnabled' => (bool) ($row->block_websites_enabled ?? false), 'lateArrivalGraceMinutes' => (int) ($row->late_arrival_grace_minutes ?? 10), 'earlyDepartureGraceMinutes' => (int) ($row->early_departure_grace_minutes ?? 10), 'policyRevision' => (int) ($row->policy_revision ?? 1), 'updateFeedUrl' => $row->update_feed_url ?? '', 'clientKeyPrefix' => $row->client_key_prefix ?? config('worklive.client_key_prefix'), 'hasAppPassword' => !empty($row->app_password_hash)]]);
    }

    public function saveSettings(Request $request)
    {
        $data = $request->validate(['companyName' => ['nullable','string','max:255'], 'businessHoursStart' => ['nullable','string','max:10'], 'businessHoursEnd' => ['nullable','string','max:10'], 'productiveAppsList' => ['nullable','array'], 'unproductiveAppsList' => ['nullable','array'], 'productiveDomainsList' => ['nullable','array'], 'unproductiveDomainsList' => ['nullable','array'], 'agentSampleIntervalSeconds' => ['nullable','integer','min:5','max:3600'], 'agentBatchIntervalSeconds' => ['nullable','integer','min:30','max:86400'], 'agentPollIntervalSeconds' => ['nullable','integer','min:10','max:3600'], 'blockWebsitesEnabled' => ['nullable','boolean'], 'lateArrivalGraceMinutes' => ['nullable','integer','min:0','max:240'], 'earlyDepartureGraceMinutes' => ['nullable','integer','min:0','max:240'], 'updateFeedUrl' => ['nullable','string','max:1000'], 'clientKeyPrefix' => ['nullable','string','max:12'], 'appPassword' => ['nullable','string','max:255']]);
        $values = ['company_name' => $data['companyName'] ?? '', 'business_hours_start' => $data['businessHoursStart'] ?? '08:00', 'business_hours_end' => $data['businessHoursEnd'] ?? '18:00', 'productive_apps_list' => json_encode($data['productiveAppsList'] ?? []), 'unproductive_apps_list' => json_encode($data['unproductiveAppsList'] ?? []), 'productive_domains_list' => json_encode($data['productiveDomainsList'] ?? []), 'unproductive_domains_list' => json_encode($data['unproductiveDomainsList'] ?? []), 'agent_sample_interval_seconds' => $data['agentSampleIntervalSeconds'] ?? 15, 'agent_batch_interval_seconds' => $data['agentBatchIntervalSeconds'] ?? 300, 'agent_poll_interval_seconds' => $data['agentPollIntervalSeconds'] ?? 30, 'block_websites_enabled' => (int) ($data['blockWebsitesEnabled'] ?? false), 'late_arrival_grace_minutes' => $data['lateArrivalGraceMinutes'] ?? 10, 'early_departure_grace_minutes' => $data['earlyDepartureGraceMinutes'] ?? 10, 'policy_revision' => (int) floor(microtime(true) * 1000), 'update_feed_url' => $data['updateFeedUrl'] ?? '', 'client_key_prefix' => Str::upper($data['clientKeyPrefix'] ?? config('worklive.client_key_prefix'))];
        if (!empty($data['appPassword'])) $values['app_password_hash'] = Hash::make($data['appPassword']);
        DB::table('company_settings')->updateOrInsert(['company_id' => $this->company()], $values + ['updated_at' => now()]);
        return response()->json(['ok' => true]);
    }

    public function admins() { return response()->json(['ok' => true, 'admins' => DB::table('authorized_admins')->where('company_id', $this->company())->orderBy('email')->get()->map(fn ($a) => ['email' => $a->email, 'addedAt' => $a->added_at, 'addedBy' => $a->added_by, 'hasPassword' => !empty($a->password_hash)])]); }
    public function addAdmin(Request $request) { $data = $request->validate(['email' => ['required','email'], 'password' => ['required','string','min:8'], 'addedBy' => ['nullable','string','max:255']]); DB::table('authorized_admins')->updateOrInsert(['email' => strtolower($data['email'])], ['company_id' => $this->company(), 'added_at' => now(), 'added_by' => $data['addedBy'] ?? session('worklive_admin.email','Administrador'), 'password_hash' => Hash::make($data['password'])]); return response()->json(['ok' => true]); }
    public function removeAdmin(string $email) { if (strtolower($email) === strtolower(env('ADMIN_BOOTSTRAP_EMAIL','admin@empresa.com'))) return response()->json(['ok'=>false,'error'=>'No se puede eliminar al administrador por defecto.'],403); DB::table('authorized_admins')->where('company_id',$this->company())->where('email',$email)->delete(); return response()->json(['ok'=>true]); }

    public function events(Request $request) { $query = DB::table('activity_events')->where('company_id',$this->company())->orderByDesc('event_timestamp'); if ($request->filled('employeeId')) $query->where('employee_id',$request->string('employeeId')); if ($request->filled('eventType')) $query->where('event_type',$request->string('eventType')); $events=$query->limit(min((int)$request->query('count',80),500))->get(); return response()->json(['ok'=>true,'events'=>$events->map(fn($e)=>['id'=>$e->id,'employeeId'=>$e->employee_id,'employeeName'=>$e->employee_name,'department'=>$e->department,'timestamp'=>$e->event_timestamp,'eventType'=>$e->event_type,'app'=>$e->app,'title'=>$e->title,'domain'=>$e->domain,'duration'=>(int)$e->duration,'agentId'=>$e->agent_id])]); }
    public function summaries(Request $request) { $query=DB::table('daily_summaries')->where('company_id',$this->company())->orderByDesc('summary_date'); if($request->filled('employeeId')) $query->where('employee_id',$request->string('employeeId')); $rows=$query->limit(500)->get(); return response()->json(['ok'=>true,'summaries'=>$rows->map(fn($s)=>['id'=>$s->id,'employeeId'=>$s->employee_id,'employeeName'=>$s->employee_name,'department'=>$s->department,'country'=>$s->country,'date'=>$s->summary_date,'totalActiveSeconds'=>(int)$s->total_active_seconds,'totalIdleSeconds'=>(int)$s->total_idle_seconds,'totalLockedSeconds'=>(int)$s->total_locked_seconds,'firstActivity'=>$s->first_activity,'lastActivity'=>$s->last_activity,'topApps'=>$this->jsonList($s->top_apps),'topDomains'=>$this->jsonList($s->top_domains)])]); }

    public function policies() { $profiles=DB::table('usage_policy_profiles')->where('company_id',$this->company())->orderBy('name')->get(); $members=DB::table('usage_policy_members')->where('company_id',$this->company())->get()->groupBy('profile_id'); return response()->json(['ok'=>true,'profiles'=>$profiles->map(fn($p)=>['id'=>$p->id,'name'=>$p->name,'description'=>$p->description,'blockedDomains'=>$this->jsonList($p->blocked_domains),'allowedDomains'=>$this->jsonList($p->allowed_domains),'productiveApps'=>$this->jsonList($p->productive_apps),'unproductiveApps'=>$this->jsonList($p->unproductive_apps),'blockedApps'=>$this->jsonList($p->blocked_apps),'memberEmployeeIds'=>($members[$p->id]??collect())->pluck('employee_id')->values(),'createdAt'=>$p->created_at,'updatedAt'=>$p->updated_at])]); }
    public function savePolicy(Request $request, ?string $id=null) { $data=$request->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string'],'blockedDomains'=>['nullable','array'],'allowedDomains'=>['nullable','array'],'productiveApps'=>['nullable','array'],'unproductiveApps'=>['nullable','array'],'blockedApps'=>['nullable','array'],'memberEmployeeIds'=>['nullable','array']]); $id=$id ?: 'policy-'.Str::lower(Str::random(18)); $values=['company_id'=>$this->company(),'name'=>$data['name'],'description'=>$data['description']??'','blocked_domains'=>json_encode($data['blockedDomains']??[]),'allowed_domains'=>json_encode($data['allowedDomains']??[]),'productive_apps'=>json_encode($data['productiveApps']??[]),'unproductive_apps'=>json_encode($data['unproductiveApps']??[]),'blocked_apps'=>json_encode($data['blockedApps']??[]),'updated_at'=>now()]; DB::table('usage_policy_profiles')->updateOrInsert(['id'=>$id,'company_id'=>$this->company()],$values+['created_at'=>now()]); if(array_key_exists('memberEmployeeIds',$data)){DB::table('usage_policy_members')->where('company_id',$this->company())->where('profile_id',$id)->delete(); foreach(array_unique($data['memberEmployeeIds']) as $employeeId) DB::table('usage_policy_members')->insert(['company_id'=>$this->company(),'employee_id'=>$employeeId,'profile_id'=>$id,'assigned_at'=>now()]);} return response()->json(['ok'=>true,'id'=>$id]); }
    public function deletePolicy(string $id) { DB::table('usage_policy_profiles')->where('company_id',$this->company())->where('id',$id)->delete(); return response()->json(['ok'=>true]); }
    public function members(Request $request, string $id) { $data=$request->validate(['employeeIds'=>['required','array']]); DB::table('usage_policy_members')->where('company_id',$this->company())->where('profile_id',$id)->delete(); foreach(array_unique($data['employeeIds']) as $employeeId) DB::table('usage_policy_members')->insert(['company_id'=>$this->company(),'employee_id'=>$employeeId,'profile_id'=>$id,'assigned_at'=>now()]); return response()->json(['ok'=>true]); }
    public function pushPolicies() { $revision=(int) floor(microtime(true) * 1000); DB::table('company_settings')->where('company_id',$this->company())->update(['policy_revision'=>$revision,'updated_at'=>now()]); return response()->json(['ok'=>true,'policyRevision'=>$revision]); }
}
