<div id="employee-crud-modal" class="employee-crud-backdrop hidden" aria-hidden="true">
  <form id="employee-crud-form" method="post" action="{{ route('employees.store') }}" class="employee-crud-dialog">
    @csrf <input id="crud-method" type="hidden" name="_method" value="">
    <header class="employee-crud-header"><div><span id="crud-title" class="employee-crud-kicker">Nuevo empleado</span><h3>Ficha del colaborador</h3><p>Administra la ficha y la KEY para vincular la aplicación cliente.</p></div><button id="crud-close" type="button" aria-label="Cerrar modal" class="employee-crud-close">×</button></header>
    <div class="employee-crud-fields">
      <label>ID interno<input id="crud-id" readonly></label>
      <label>Estado<select id="crud-status" name="status"><option value="offline">Offline</option><option value="online">Online (Disponible)</option><option value="active">Activo (Live)</option><option value="idle">Inactivo (Idle)</option><option value="locked">Bloqueado</option></select></label>
      <label class="employee-crud-wide">Nombre completo<input id="crud-name" name="name" required placeholder="Ej. Juan Pérez"></label>
      <label>Departamento / área<select id="crud-department" name="department"><option>Desarrollo de Software</option><option>Ventas y Clientes</option><option>Marketing Digital</option><option>Soporte Técnico</option><option>Talento Humano</option><option value="__other">Otro / escribir área…</option></select><input id="crud-department-custom" class="hidden" placeholder="Escribe el departamento o área"></label>
      <label>País<select id="crud-country" name="country"><option>México</option><option>Colombia</option><option>Estados Unidos</option><option>Brasil</option><option>España</option><option>Argentina</option><option>Chile</option><option>Perú</option></select></label>
      <label class="employee-crud-wide">Zona horaria<input id="crud-timezone" name="timezone" readonly value="America/Mexico_City (UTC-6)"></label>
    </div>
    <section class="employee-crud-key"><span>Key de vinculación del cliente</span><div><input id="crud-key" name="client_key"><button id="crud-generate" type="button" data-prefix="{{ $clientKeyPrefix }}">Generar</button><button id="crud-copy" type="button">▣ Copiar</button></div></section>
    <footer class="employee-crud-actions">@if($isAdmin)<button id="crud-delete" type="button" class="employee-crud-delete hidden">Eliminar empleado</button>@endif<button id="crud-cancel" type="button">Cancelar</button><button id="crud-submit">Crear empleado</button></footer>
  </form>
</div>
<script>
(() => {
 const modal=document.getElementById('employee-crud-modal'),form=document.getElementById('employee-crud-form'),title=document.getElementById('crud-title'),id=document.getElementById('crud-id'),name=document.getElementById('crud-name'),dept=document.getElementById('crud-department'),customDept=document.getElementById('crud-department-custom'),country=document.getElementById('crud-country'),timezone=document.getElementById('crud-timezone'),status=document.getElementById('crud-status'),key=document.getElementById('crud-key'),method=document.getElementById('crud-method'),submit=document.getElementById('crud-submit'),prefix=document.getElementById('crud-generate').dataset.prefix||'SAFEB';
 const zones={'México':'America/Mexico_City (UTC-6)','Colombia':'America/Bogota (UTC-5)','Estados Unidos':'America/New_York (UTC-5)','Brasil':'America/Sao_Paulo (UTC-3)','España':'Europe/Madrid (UTC+1)','Argentina':'America/Argentina/Buenos_Aires (UTC-3)','Chile':'America/Santiago (UTC-4)','Perú':'America/Lima (UTC-5)'};
 const make=()=>{const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';return prefix.replace(/[^A-Z0-9]/gi,'').slice(0,12).toUpperCase()+'-'+Array.from({length:4},()=>Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('')).join('-')};
 const syncDepartment=()=>{const other=dept.value==='__other';customDept.classList.toggle('hidden',!other);customDept.required=other;dept.name=other?'':'department';customDept.name=other?'department':'';if(other) customDept.focus();};
 const close=()=>{modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');};
 const open=(data={})=>{const edit=!!data.id;title.textContent=edit?'Editar empleado':'Nuevo empleado';id.value=data.id||'emp-'+Date.now();name.value=data.name||'';const option=[...dept.options].find(o=>o.value===(data.department||'Desarrollo de Software'));dept.value=option?option.value:'__other';customDept.value=option?'':(data.department||'');syncDepartment();country.value=data.country||'México';timezone.value=data.timezone||zones[country.value];status.value=data.status||'offline';key.value=data.key||make();method.value=edit?'PUT':'';form.action=edit?'{{ url('/employees') }}/'+data.id:'{{ route('employees.store') }}';submit.textContent=edit?'Guardar cambios':'Crear empleado';document.getElementById('crud-delete')?.classList.toggle('hidden',!edit);modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');name.focus();};
 window.openEmployeeCrud=open; country.onchange=()=>timezone.value=zones[country.value]||timezone.value;dept.onchange=syncDepartment;document.getElementById('crud-generate').onclick=()=>key.value=make();document.getElementById('crud-copy').onclick=()=>navigator.clipboard?.writeText(key.value);document.getElementById('crud-cancel').onclick=close;document.getElementById('crud-close').onclick=close;document.getElementById('crud-delete')?.addEventListener('click',()=>{if(!confirm('¿Eliminar permanentemente a '+name.value+'? Esta acción no se puede deshacer.'))return;const deletion=document.createElement('form');deletion.method='post';deletion.action='{{ url('/employees') }}/'+id.value;deletion.innerHTML='<input type="hidden" name="_token" value="{{ csrf_token() }}"><input type="hidden" name="_method" value="DELETE">';document.body.appendChild(deletion);deletion.submit()});modal.addEventListener('click',e=>{if(e.target===modal)close()});form.addEventListener('submit',()=>syncDepartment());
 document.querySelectorAll('a').forEach(a=>{if(a.textContent.includes('Editar'))a.addEventListener('click',e=>{e.preventDefault();const row=a.closest('tr'),cells=row.querySelectorAll('td'),href=a.href.match(/employees\/([^?]+)/);open({id:href?.[1],name:cells[0].querySelector('a')?.textContent.trim(),department:cells[1].textContent.trim(),country:cells[2].textContent.replace(/^.*?\s/,'').split('\n')[0].trim(),timezone:cells[2].querySelector('span')?.textContent.trim(),status:cells[3].textContent.trim().toLowerCase().startsWith('activo')?'active':'offline',key:cells[0].querySelector('[data-copy]')?.dataset.copy})})});
})();
</script>
