@extends('layouts.app')

@section('body')
@php
    $hasAppPassword = !empty($settings?->app_password_hash);
    $input = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-xs font-semibold text-slate-800 outline-none transition focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100';
@endphp
<div class="shell">@include('partials.sidebar')<main class="main">@include('partials.header',['title'=>'Configuración · Sistema'])
<div class="content settings-workspace">
    <section class="app-section-hero mb-6"><div class="app-section-hero-copy"><p><i class="fa-solid fa-sliders" aria-hidden="true"></i> Administración corporativa</p><h2>Sistema</h2><span>Controla horarios, zona horaria, frecuencia de sincronización y parámetros del agente.</span></div><div class="app-section-hero-metrics"><div><i class="fa-solid fa-clock" aria-hidden="true"></i><small>Jornada</small><b>{{ $settings?->business_hours_start ?? '08:00' }}</b></div><div><i class="fa-solid fa-globe" aria-hidden="true"></i><small>Zona</small><b>{{ $settings?->timezone ?? 'UTC' }}</b></div><div><i class="fa-solid fa-key" aria-hidden="true"></i><small>App cliente</small><b>{{ $hasAppPassword ? 'OK' : '—' }}</b></div></div><div class="app-section-hero-actions"><button type="submit" form="settings-form"><i class="fa-solid fa-floppy-disk" aria-hidden="true"></i><span>Guardar cambios</span></button></div></section>

    @if(session('success'))<div class="mb-6 flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-semibold text-emerald-800"><i class="fa-solid fa-circle-check" aria-hidden="true"></i>{{ session('success') }} Los cambios se aplicarán instantáneamente.</div>@endif
    @if($errors->any())<div class="mb-6 flex items-center gap-2 rounded-xl border border-red-100 bg-red-50 p-4 text-xs font-semibold text-red-800"><i class="fa-solid fa-triangle-exclamation" aria-hidden="true"></i>{{ $errors->first() }}</div>@endif

    <form id="settings-form" method="post" action="{{ route('settings.save') }}" class="space-y-8">@csrf
        <section class="grid grid-cols-1 gap-6 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm md:grid-cols-4">
            <div class="md:col-span-4"><h3 class="flex items-center gap-2 text-sm font-bold text-slate-900"><i class="fa-solid fa-building text-slate-500" aria-hidden="true"></i> Operación corporativa</h3><p class="mt-1 text-xs text-slate-500">Estos valores determinan la jornada y la zona de lectura de todo el panel.</p></div>
            <label class="space-y-1.5 md:col-span-2"><span class="block font-mono text-[10px] font-bold text-slate-400">DATOS DE LA EMPRESA (NOMBRE)</span><div class="relative"><i class="fa-solid fa-building absolute left-3.5 top-3 text-slate-400" aria-hidden="true"></i><input class="{{ $input }} pl-10" name="company_name" required value="{{ old('company_name',$settings->company_name ?? config('worklive.company_name')) }}"></div></label>
            <label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold text-slate-400">ZONA HORARIA CORPORATIVA</span><select class="{{ $input }}" name="timezone" required>@php($selectedTimezone = old('timezone', $settings->timezone ?? 'America/Mexico_City'))@foreach(['America/Mexico_City'=>'Ciudad de México (UTC-6)','America/Bogota'=>'Bogotá (UTC-5)','America/Lima'=>'Lima (UTC-5)','America/New_York'=>'Nueva York (UTC-5/-4)','America/Chicago'=>'Chicago (UTC-6/-5)','America/Los_Angeles'=>'Los Ángeles (UTC-8/-7)','America/Sao_Paulo'=>'São Paulo (UTC-3)','Europe/Madrid'=>'Madrid (UTC+1/+2)','UTC'=>'UTC'] as $timezone => $label)<option value="{{ $timezone }}" @selected($selectedTimezone === $timezone)>{{ $label }}</option>@endforeach</select></label>
            <label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold text-slate-400">HORARIOS ADMINISTRATIVOS</span><span class="flex items-center gap-2"><input class="{{ $input }} min-w-0 px-1 text-center" maxlength="5" name="business_hours_start" required value="{{ old('business_hours_start',$settings->business_hours_start ?? '08:00') }}"><b class="text-xs text-slate-400">a</b><input class="{{ $input }} min-w-0 px-1 text-center" maxlength="5" name="business_hours_end" required value="{{ old('business_hours_end',$settings->business_hours_end ?? '18:00') }}"></span></label>
            <label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold text-slate-400">RETARDO DESPUÉS DE</span><span class="flex items-center gap-2"><input class="{{ $input }} text-center" type="number" min="0" max="180" name="late_arrival_grace_minutes" value="{{ old('late_arrival_grace_minutes',$settings->late_arrival_grace_minutes ?? 10) }}"><b class="text-[10px] uppercase text-slate-400">min</b></span></label>
            <label class="space-y-1.5 md:col-start-4"><span class="block font-mono text-[10px] font-bold text-slate-400">SALIDA TEMPRANA SI FALTAN</span><span class="flex items-center gap-2"><input class="{{ $input }} text-center" type="number" min="0" max="180" name="early_departure_grace_minutes" value="{{ old('early_departure_grace_minutes',$settings->early_departure_grace_minutes ?? 10) }}"><b class="text-[10px] uppercase text-slate-400">min</b></span></label>
        </section>

        <section class="space-y-5 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div><h3 class="flex items-center gap-2 text-sm font-bold text-slate-900"><i class="fa-brands fa-windows text-slate-500" aria-hidden="true"></i> Configuración del Agente Windows</h3><p class="mt-1 text-xs text-slate-500">Intervalos y credenciales consultados por la aplicación cliente.</p></div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-3"><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold text-slate-400">MEDIR CADA (SEGUNDOS)</span><input class="{{ $input }} text-center" type="number" min="5" max="300" name="agent_sample_interval_seconds" value="{{ old('agent_sample_interval_seconds',$settings->agent_sample_interval_seconds ?? 15) }}"></label><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold text-slate-400">ENVIAR DATOS CADA (SEGUNDOS)</span><input class="{{ $input }} text-center" type="number" min="30" max="3600" name="agent_batch_interval_seconds" value="{{ old('agent_batch_interval_seconds',$settings->agent_batch_interval_seconds ?? 300) }}"></label><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold text-slate-400">CONSULTAR INSTRUCCIONES CADA (SEGUNDOS)</span><input class="{{ $input }} text-center" type="number" min="10" max="3600" name="agent_poll_interval_seconds" value="{{ old('agent_poll_interval_seconds',$settings->agent_poll_interval_seconds ?? 30) }}"><span class="block text-[10px] text-slate-400">Determina cuándo el cliente consulta solicitudes y cambios de política.</span></label></div>
            <label class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><span><b class="block font-mono text-[10px] font-bold uppercase text-slate-500">Bloquear dominios no productivos</b><span class="mt-1 block text-xs text-slate-500">Aplica las reglas web activas de Políticas de uso.</span></span><input class="h-5 w-5 accent-indigo-600" type="checkbox" name="block_websites_enabled" value="1" @checked(old('block_websites_enabled',$settings->block_websites_enabled ?? false))></label>
            <label class="block rounded-xl border border-slate-200 bg-slate-50 p-4"><span class="block font-mono text-[10px] font-bold uppercase text-slate-500">Prefijo para KEY de vinculación</span><span class="mb-3 mt-1 block text-xs text-slate-500">Texto con el que iniciarán las nuevas KEYs del cliente. Ejemplo: <b>SAFEB</b>-XXXX-XXXX-XXXX-XXXX.</span><input class="{{ $input }} bg-white font-mono font-black tracking-wider" name="client_key_prefix" maxlength="12" required value="{{ old('client_key_prefix',$settings->client_key_prefix ?? 'SAFEB') }}" oninput="this.value=this.value.toUpperCase().replace(/[^A-Z0-9]/g,'')"></label>
            <label class="block rounded-xl border border-slate-200 bg-slate-50 p-4"><span class="block font-mono text-[10px] font-bold uppercase text-slate-500">URL de actualizaciones del cliente</span><span class="mb-3 mt-1 block text-xs text-slate-500">URL pública al archivo <b>latest.json</b> que usará WorkLive Tracker al presionar “Buscar actualización”.</span><input class="{{ $input }} bg-white" type="url" name="update_feed_url" value="{{ old('update_feed_url',$settings->update_feed_url ?? '') }}" placeholder="https://tu-dominio.com/worklive-tracker/latest.json"></label>
            <div class="flex flex-col justify-between gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4 md:flex-row md:items-center"><div class="max-w-xl"><span class="block font-mono text-[10px] font-bold uppercase text-slate-500">Contraseña para App Cliente</span><p class="mt-1 text-xs text-slate-500">Se solicitará para cerrar el Tracker y mostrar rutas de archivos locales. {{ $hasAppPassword ? 'Ya existe una contraseña configurada.' : 'Aún no hay contraseña configurada.' }}</p></div><div class="relative w-full md:w-80"><input id="app-password" class="{{ $input }} bg-white pr-10" type="password" name="app_password" minlength="8" placeholder="{{ $hasAppPassword ? 'Nueva contraseña opcional' : 'Crear contraseña' }}"><button class="absolute right-2 top-1/2 -translate-y-1/2 p-1 text-slate-400" type="button" data-password-toggle="app-password" aria-label="Mostrar contraseña"><i class="fa-regular fa-eye"></i></button></div></div>
            <div class="hidden"><textarea name="productive_apps_list">{{ old('productive_apps_list',$settings->productive_apps_list ?? '') }}</textarea><textarea name="unproductive_apps_list">{{ old('unproductive_apps_list',$settings->unproductive_apps_list ?? '') }}</textarea><textarea name="productive_domains_list">{{ old('productive_domains_list',$settings->productive_domains_list ?? '') }}</textarea><textarea name="unproductive_domains_list">{{ old('unproductive_domains_list',$settings->unproductive_domains_list ?? '') }}</textarea></div>
        </section>
    </form>
</div></main></div>
<script>document.querySelectorAll('[data-password-toggle]').forEach((button)=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordToggle);input.type=input.type==='password'?'text':'password';button.innerHTML=input.type==='password'?'<i class="fa-regular fa-eye"></i>':'<i class="fa-regular fa-eye-slash"></i>';}));</script>
@endsection
