@extends('layouts.app')

@section('body')
@php
    $hex = fn ($field, $fallback) => old($field, preg_match('/^#[0-9A-Fa-f]{6}$/', (string) ($settings?->{$field} ?? '')) ? $settings->{$field} : $fallback);
    $text = fn ($field, $fallback) => old($field, $settings?->{$field} ?: $fallback);
    $colors = [['color_primary','Color principal','#4f46e5','Acciones y selección'],['color_secondary','Color secundario','#312e81','Profundidad de encabezados'],['color_accent','Color de acento','#06b6d4','Indicadores destacados'],['color_sidebar','Fondo del menú','#0f172a','Barra lateral'],['color_sidebar_text','Texto del menú','#cbd5e1','Navegación no seleccionada'],['color_page','Fondo de páginas','#f8fafc','Área de trabajo'],['color_surface','Superficies','#ffffff','Tarjetas y formularios'],['color_text','Texto principal','#0f172a','Títulos y contenido']];
    $menuFields = [['menu_dashboard','Tablero principal','Tablero Principal'],['menu_employees','Empleados','Lista de Empleados'],['menu_reports','Reportes','Reportes y Exportación'],['menu_policies','Políticas','Políticas de Uso'],['menu_time_clock','Reloj checador','RH · Reloj Checador'],['menu_settings','Configuración','Configuración'],['menu_system','Submenú: Sistema','Sistema'],['menu_administrators','Submenú: Administradores','Administradores'],['menu_personalization','Submenú: Personalización','Personalización']];
    $logoBackgroundEnabled = old('logo_background_enabled', $settings?->logo_background_enabled ?? true);
@endphp
<div class="shell">@include('partials.sidebar')<main class="main">@include('partials.header',['title'=>'Configuración · Personalización'])
<div class="content settings-workspace personalization-workspace">
    <section class="app-section-hero mb-6"><div class="app-section-hero-copy"><p><i class="fa-solid fa-wand-magic-sparkles" aria-hidden="true"></i> Identidad del panel</p><h2>{{ $workliveBrand?->menu_personalization ?: 'Personalización' }}</h2><span>Define la identidad visual, los colores y los nombres que verá tu equipo en todo el sistema.</span></div><div class="app-section-hero-metrics"><div><i class="fa-solid fa-palette" aria-hidden="true"></i><small>Paleta</small><b>8 colores</b></div><div><i class="fa-solid fa-bars" aria-hidden="true"></i><small>Menú</small><b>9 etiquetas</b></div></div><div class="app-section-hero-actions"><button type="submit" form="personalization-form"><i class="fa-solid fa-floppy-disk" aria-hidden="true"></i><span>Aplicar identidad</span></button></div></section>
    @if(session('success'))<div class="mb-6 flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-semibold text-emerald-800"><i class="fa-solid fa-circle-check"></i>{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-6 flex items-center gap-2 rounded-xl border border-red-100 bg-red-50 p-4 text-xs font-semibold text-red-800"><i class="fa-solid fa-triangle-exclamation"></i>{{ $errors->first() }}</div>@endif

    <form id="personalization-form" method="post" action="{{ route('settings.personalization.save') }}" enctype="multipart/form-data" class="space-y-7">@csrf
        <section class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div class="mb-6"><h3 class="flex items-center gap-2 text-sm font-bold text-slate-900"><i class="fa-solid fa-signature text-indigo-500"></i> Identidad del sistema</h3><p class="mt-1 text-xs text-slate-500">El nombre y el ícono se reflejan en la barra lateral, pestaña del navegador y favicon.</p></div><div class="grid grid-cols-1 gap-5 md:grid-cols-2"><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold uppercase text-slate-400">Nombre del sistema</span><input class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-xs font-semibold text-slate-800 outline-none transition focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100" name="brand_name" maxlength="100" required value="{{ $text('brand_name','WorkLive Pro') }}"></label><label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold uppercase text-slate-400">Subtítulo</span><input class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-xs font-semibold text-slate-800 outline-none transition focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100" name="brand_subtitle" maxlength="160" value="{{ $text('brand_subtitle','Live Operations') }}"></label></div>
            <div class="mt-6 flex flex-col gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:flex-row sm:items-center"><div id="brand-icon-preview" class="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-xl text-xl text-white shadow" style="background:{{ $logoBackgroundEnabled ? $hex('color_logo_background','#4f46e5') : 'transparent' }}">@if(!empty($settings?->brand_icon_path))<img class="h-full w-full object-cover" src="{{ asset('storage/'.$settings->brand_icon_path) }}" alt="Ícono actual">@else<i class="fa-solid fa-bolt"></i>@endif</div><div class="min-w-0 flex-1"><label><span class="block font-mono text-[10px] font-bold uppercase text-slate-400">Ícono y favicon</span><span class="mt-1 block text-xs text-slate-500">PNG, JPG, WEBP o ICO. Máximo 2 MB. Se usa también como favicon.</span><input id="brand-icon-input" class="mt-3 block w-full text-xs text-slate-500 file:mr-3 file:rounded-lg file:border-0 file:bg-indigo-100 file:px-3 file:py-2 file:text-xs file:font-bold file:text-indigo-700 hover:file:bg-indigo-200" type="file" name="brand_icon" accept=".png,.jpg,.jpeg,.webp,.ico"></label><div class="mt-4 flex flex-wrap items-center gap-4"><label class="flex items-center gap-2 text-xs font-semibold text-slate-700"><input id="logo-background-enabled" class="h-4 w-4 accent-indigo-600" type="checkbox" name="logo_background_enabled" value="1" @checked($logoBackgroundEnabled)> Mostrar fondo de logo</label><label class="flex items-center gap-2 text-xs font-semibold text-slate-700">Color de fondo <input id="logo-background-color" class="h-8 w-9 cursor-pointer rounded border-0 bg-transparent p-0" type="color" name="color_logo_background" value="{{ $hex('color_logo_background','#4f46e5') }}"></label></div></div></div></section>

        <section class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div class="mb-6"><h3 class="flex items-center gap-2 text-sm font-bold text-slate-900"><i class="fa-solid fa-swatchbook text-indigo-500"></i> Paleta de colores</h3><p class="mt-1 text-xs text-slate-500">Todos los valores aceptan código hexadecimal y se previsualizan al instante.</p></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($colors as [$field,$label,$fallback,$description])<label class="brand-color-control rounded-xl border border-slate-200 bg-slate-50 p-4"><span class="flex items-start justify-between gap-3"><span><b class="block text-xs text-slate-800">{{ $label }}</b><small class="mt-1 block leading-relaxed text-[10px] text-slate-500">{{ $description }}</small></span><input class="h-9 w-9 cursor-pointer rounded-lg border-0 bg-transparent p-0" type="color" value="{{ $hex($field,$fallback) }}" data-color-picker="{{ $field }}"></span><span class="mt-4 flex items-center gap-2"><i class="h-7 w-7 rounded-lg border border-slate-200 shadow-sm" data-color-swatch="{{ $field }}" style="background:{{ $hex($field,$fallback) }}"></i><input class="w-full bg-transparent font-mono text-xs font-bold uppercase text-slate-700 outline-none" name="{{ $field }}" maxlength="7" value="{{ $hex($field,$fallback) }}" data-color-value="{{ $field }}"></span></label>@endforeach</div></section>

        <section class="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div class="mb-6"><h3 class="flex items-center gap-2 text-sm font-bold text-slate-900"><i class="fa-solid fa-bars-staggered text-indigo-500"></i> Nombres del menú</h3><p class="mt-1 text-xs text-slate-500">Renombra cada apartado sin alterar sus rutas ni funcionalidades.</p></div><div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($menuFields as [$field,$label,$fallback])<label class="space-y-1.5"><span class="block font-mono text-[10px] font-bold uppercase text-slate-400">{{ $label }}</span><input class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-xs font-semibold text-slate-800 outline-none transition focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100" name="{{ $field }}" maxlength="80" required value="{{ $text($field,$fallback) }}"></label>@endforeach</div></section>
    </form>
</div></main></div>
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-color-picker]').forEach(picker=>{const key=picker.dataset.colorPicker,value=document.querySelector(`[data-color-value="${key}"]`),swatch=document.querySelector(`[data-color-swatch="${key}"]`);const update=(color)=>{if(!/^#[0-9a-f]{6}$/i.test(color))return;picker.value=color;value.value=color.toUpperCase();swatch.style.background=color;document.documentElement.style.setProperty(`--wl-${key.replace('color_','').replaceAll('_','-')}`,color)};picker.addEventListener('input',()=>update(picker.value));value.addEventListener('change',()=>update(value.value))});const preview=document.getElementById('brand-icon-preview'),logoColor=document.getElementById('logo-background-color'),logoBackground=document.getElementById('logo-background-enabled');const updateLogo=()=>{preview.style.background=logoBackground.checked?logoColor.value:'transparent'};logoColor?.addEventListener('input',updateLogo);logoBackground?.addEventListener('change',updateLogo);document.getElementById('brand-icon-input')?.addEventListener('change',(event)=>{const file=event.target.files?.[0];if(!file)return;preview.innerHTML='';const image=document.createElement('img');image.className='h-full w-full object-cover';image.src=URL.createObjectURL(file);preview.appendChild(image)})});</script>
@endsection
